name: Deploy to CapRover

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Descargar el repositorio
      - name: Check out repository
        uses: actions/checkout@v4

      # 2️⃣ Deploy a CapRover
      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.APP_NAME }}
          token: ${{ secrets.APP_TOKEN }}
