name: Deploy to CapRover

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@main
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.CAPROVER_APP_NAME }}
          token: ${{ secrets.CAPROVER_APP_TOKEN }}
