name: Deploy to CapRover

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CapRover CLI
        run: npm install -g caprover

      - name: Deploy to CapRover
        run: |
          caprover deploy \
            --caproverUrl ${{ secrets.CAPROVER_SERVER }} \
            --appToken ${{ secrets.CAPROVER_APP_TOKEN }} \
            --appName ${{ secrets.CAPROVER_APP_NAME }}
